name: Generate Snake
 
on:
  # ให้รันทุกวันตอนเที่ยงคืน
  schedule:
    - cron: "0 0 * * *" 
  # หรือจะกดรันเองก็ได้
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # ชื่อบัญชี github ข���งคุณ
          github_user_name: chakracha1
          # ไฟล์ที่จะได้ออกมา
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
