name: Generate Snake
 
on:
  # ให้รันทุกวันตอนเที่ยงคืน
  schedule:
    - cron: "0 0 * * *" 
  # หรือจะกดรันเองก็ได้
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: chakracha1
          outputs: |
            # เปลี่ยนสีงู (color_snake) เป็นสีฟ้าสว่าง #00ffff (Cyan)
            # เปลี่ยนสีจุด (color_dots) เป็นโทนมืดไล่ไปสว่าง (น้ำเงินเข้ม -> ฟ้า)
            dist/github-contribution-grid-snake.svg?color_snake=#00ffff&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
